# Generated by Django 5.0.2 on 2024-02-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('logo_path', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('origin_country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionCountry',
            fields=[
                ('iso_3166_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('backdrop_path', models.CharField(max_length=255, null=True)),
                ('homepage', models.URLField(null=True)),
                ('original_language', models.CharField(max_length=2)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=255, null=True)),
                ('release_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SpokenLanguage',
            fields=[
                ('iso_639_1', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('english_name', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField()),
                ('backdrop_path', models.CharField(max_length=255, null=True)),
                ('budget', models.IntegerField()),
                ('homepage', models.URLField(null=True)),
                ('imdb_id', models.CharField(max_length=255)),
                ('original_language', models.CharField(max_length=2)),
                ('original_title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.CharField(max_length=255, null=True)),
                ('release_date', models.DateField()),
                ('revenue', models.IntegerField()),
                ('runtime', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=255)),
                ('tagline', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('video', models.BooleanField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('genres', models.ManyToManyField(to='recommendations.genre')),
                ('production_companies', models.ManyToManyField(to='recommendations.productioncompany')),
                ('production_countries', models.ManyToManyField(to='recommendations.productioncountry')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.movie')),
            ],
        ),
    ]
