# Generated by Django 5.0.2 on 2024-02-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser'),
        ),
        migrations.AddField(
            model_name='serie',
            name='genres',
            field=models.ManyToManyField(to='recommendations.genre'),
        ),
        migrations.AddField(
            model_name='serie',
            name='production_companies',
            field=models.ManyToManyField(to='recommendations.productioncompany'),
        ),
        migrations.AddField(
            model_name='serie',
            name='production_countries',
            field=models.ManyToManyField(to='recommendations.productioncountry'),
        ),
        migrations.AddField(
            model_name='serie',
            name='spoken_languages',
            field=models.ManyToManyField(to='recommendations.spokenlanguage'),
        ),
        migrations.AddField(
            model_name='movie',
            name='spoken_languages',
            field=models.ManyToManyField(to='recommendations.spokenlanguage'),
        ),
    ]
